version: "3":
services:
  frontend:
    container_name: textonomy_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    ports:
      - 8888:80

  backend:
    restart: always
    container_name: textonomy_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 80

